export enum OnboardingStatus {
  IN_PROGRESS = 'IN_PROGRESS',
  WAITING_MANUAL_VERIFICATION = 'WAITING_MANUAL_VERIFICATION',
  MANUAL_VERIFICATION_COMPLETED = 'MANUAL_VERIFICATION_COMPLETED',
  INITIAL_APPROVAL = 'INITIAL_APPROVAL',
  GO_LIVE = 'GO_LIVE',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED'
}
