export enum UserStatus {
  PHONE_VERIFICATION_PENDING = 'PHONE_VERIFICATION_PENDING',
  PHONE_VERIFIED = 'PHONE_VERIFIED',
  ACCOUNT_CREATED = 'ACCOUNT_CREATED',
  CREDENTIAL_SENT = 'CREDENTIAL_SENT',
  FIRST_LOGIN_PENDING = 'FIRST_LOGIN_PENDING',
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE'
}
